name: wallet-creator
base: core22
version: '1.0.0'
summary: Am ethereum wallet creator with a primary account number association
description: |
  Am ethereum wallet creator with a primary account number association

grade: stable
confinement: strict

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
